services:
  - type: web
    name: terabox-downloader-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHANNEL_USERNAME
        value: nrtecno2
      - key: CHANNEL_ID
        sync: false
      - key: PRIVATE_CHANNEL_ID
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: PORT
        value: 10000
